// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository Service Specification
 *
 * The Full Profile of the Asset Administration Shell Repository Service Specification as part of the [Specification of the Asset Administration Shell: Part 2](https://industrialdigitaltwin.org/en/content-hub/aasspecifications).   Copyright: Industrial Digital Twin Association (IDTA) 2025
 *
 * API version: V3.1.1_SSP-001
 * Contact: info@idtwin.org
 */

package openapi

import (
	"context"
	"net/http"
	"os"

	"github.com/aas-core-works/aas-core3.1-golang/types"
	model "github.com/eclipse-basyx/basyx-go-components/internal/common/model"
)

type (
	AssetAdministrationShell  = types.IAssetAdministrationShell
	AssetInformation          = types.IAssetInformation
	Reference                 = types.IReference
	Submodel                  = types.ISubmodel
	SubmodelMetadata          = model.SubmodelMetadata
	SubmodelElement           = types.ISubmodelElement
	SubmodelElementMetadata   = model.SubmodelElementMetadata
	SubmodelElementValue      = model.SubmodelElementValue
	OperationRequest          = model.OperationRequest
	OperationRequestValueOnly = model.OperationRequestValueOnly
)

// AssetAdministrationShellRepositoryAPIAPIRouter defines the required methods for binding the api requests to a responses for the AssetAdministrationShellRepositoryAPIAPI
// The AssetAdministrationShellRepositoryAPIAPIRouter implementation should parse necessary information from the http request,
// pass the data to a AssetAdministrationShellRepositoryAPIAPIServicer to perform the required actions, then write the service results to the http response.
type AssetAdministrationShellRepositoryAPIAPIRouter interface {
	GetAllAssetAdministrationShells(http.ResponseWriter, *http.Request)
	PostAssetAdministrationShell(http.ResponseWriter, *http.Request)
	GetAllAssetAdministrationShellsReference(http.ResponseWriter, *http.Request)
	GetAssetAdministrationShellById(http.ResponseWriter, *http.Request)
	PutAssetAdministrationShellById(http.ResponseWriter, *http.Request)
	DeleteAssetAdministrationShellById(http.ResponseWriter, *http.Request)
	GetAssetAdministrationShellByIdReferenceAasRepository(http.ResponseWriter, *http.Request)
	GetAssetInformationAasRepository(http.ResponseWriter, *http.Request)
	PutAssetInformationAasRepository(http.ResponseWriter, *http.Request)
	GetThumbnailAasRepository(http.ResponseWriter, *http.Request)
	PutThumbnailAasRepository(http.ResponseWriter, *http.Request)
	DeleteThumbnailAasRepository(http.ResponseWriter, *http.Request)
	GetAllSubmodelReferencesAasRepository(http.ResponseWriter, *http.Request)
	PostSubmodelReferenceAasRepository(http.ResponseWriter, *http.Request)
	DeleteSubmodelReferenceAasRepository(http.ResponseWriter, *http.Request)
	GetSubmodelByIdAasRepository(http.ResponseWriter, *http.Request)
	PutSubmodelByIdAasRepository(http.ResponseWriter, *http.Request)
	DeleteSubmodelByIdAasRepository(http.ResponseWriter, *http.Request)
	PatchSubmodelAasRepository(http.ResponseWriter, *http.Request)
	GetSubmodelByIdMetadataAasRepository(http.ResponseWriter, *http.Request)
	PatchSubmodelByIdMetadataAasRepository(http.ResponseWriter, *http.Request)
	GetSubmodelByIdValueOnlyAasRepository(http.ResponseWriter, *http.Request)
	PatchSubmodelByIdValueOnlyAasRepository(http.ResponseWriter, *http.Request)
	GetSubmodelByIdReferenceAasRepository(http.ResponseWriter, *http.Request)
	GetSubmodelByIdPathAasRepository(http.ResponseWriter, *http.Request)
	GetAllSubmodelElementsAasRepository(http.ResponseWriter, *http.Request)
	PostSubmodelElementAasRepository(http.ResponseWriter, *http.Request)
	GetAllSubmodelElementsMetadataAasRepository(http.ResponseWriter, *http.Request)
	GetAllSubmodelElementsValueOnlyAasRepository(http.ResponseWriter, *http.Request)
	GetAllSubmodelElementsReferenceAasRepository(http.ResponseWriter, *http.Request)
	GetAllSubmodelElementsPathAasRepository(http.ResponseWriter, *http.Request)
	GetSubmodelElementByPathAasRepository(http.ResponseWriter, *http.Request)
	PutSubmodelElementByPathAasRepository(http.ResponseWriter, *http.Request)
	PostSubmodelElementByPathAasRepository(http.ResponseWriter, *http.Request)
	DeleteSubmodelElementByPathAasRepository(http.ResponseWriter, *http.Request)
	PatchSubmodelElementValueByPathAasRepository(http.ResponseWriter, *http.Request)
	GetSubmodelElementByPathMetadataAasRepository(http.ResponseWriter, *http.Request)
	PatchSubmodelElementValueByPathMetadata(http.ResponseWriter, *http.Request)
	GetSubmodelElementByPathValueOnlyAasRepository(http.ResponseWriter, *http.Request)
	PatchSubmodelElementValueByPathValueOnly(http.ResponseWriter, *http.Request)
	GetSubmodelElementByPathReferenceAasRepository(http.ResponseWriter, *http.Request)
	GetSubmodelElementByPathPathAasRepository(http.ResponseWriter, *http.Request)
	GetFileByPathAasRepository(http.ResponseWriter, *http.Request)
	PutFileByPathAasRepository(http.ResponseWriter, *http.Request)
	DeleteFileByPathAasRepository(http.ResponseWriter, *http.Request)
	InvokeOperationAasRepository(http.ResponseWriter, *http.Request)
	InvokeOperationValueOnlyAasRepository(http.ResponseWriter, *http.Request)
	InvokeOperationAsyncAasRepository(http.ResponseWriter, *http.Request)
	InvokeOperationAsyncValueOnlyAasRepository(http.ResponseWriter, *http.Request)
	GetOperationAsyncStatusAasRepository(http.ResponseWriter, *http.Request)
	GetOperationAsyncResultAasRepository(http.ResponseWriter, *http.Request)
	GetOperationAsyncResultValueOnlyAasRepository(http.ResponseWriter, *http.Request)
}

// DescriptionAPIAPIRouter defines the required methods for binding the api requests to a responses for the DescriptionAPIAPI
// The DescriptionAPIAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DescriptionAPIAPIServicer to perform the required actions, then write the service results to the http response.
type DescriptionAPIAPIRouter interface {
	GetSelfDescription(http.ResponseWriter, *http.Request)
}

// SerializationAPIAPIRouter defines the required methods for binding the api requests to a responses for the SerializationAPIAPI
// The SerializationAPIAPIRouter implementation should parse necessary information from the http request,
// pass the data to a SerializationAPIAPIServicer to perform the required actions, then write the service results to the http response.
type SerializationAPIAPIRouter interface {
	GenerateSerializationByIds(http.ResponseWriter, *http.Request)
}

// AssetAdministrationShellRepositoryAPIAPIServicer defines the api actions for the AssetAdministrationShellRepositoryAPIAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type AssetAdministrationShellRepositoryAPIAPIServicer interface {
	GetAllAssetAdministrationShells(context.Context, []string, string, int32, string) (model.ImplResponse, error)
	PostAssetAdministrationShell(context.Context, AssetAdministrationShell) (model.ImplResponse, error)
	GetAllAssetAdministrationShellsReference(context.Context, []string, string, int32, string) (model.ImplResponse, error)
	GetAssetAdministrationShellById(context.Context, string) (model.ImplResponse, error)
	PutAssetAdministrationShellById(context.Context, string, AssetAdministrationShell) (model.ImplResponse, error)
	DeleteAssetAdministrationShellById(context.Context, string) (model.ImplResponse, error)
	GetAssetAdministrationShellByIdReferenceAasRepository(context.Context, string) (model.ImplResponse, error)
	GetAssetInformationAasRepository(context.Context, string) (model.ImplResponse, error)
	PutAssetInformationAasRepository(context.Context, string, AssetInformation) (model.ImplResponse, error)
	GetThumbnailAasRepository(context.Context, string) (model.ImplResponse, error)
	PutThumbnailAasRepository(context.Context, string, string, *os.File) (model.ImplResponse, error)
	DeleteThumbnailAasRepository(context.Context, string) (model.ImplResponse, error)
	GetAllSubmodelReferencesAasRepository(context.Context, string, int32, string) (model.ImplResponse, error)
	PostSubmodelReferenceAasRepository(context.Context, string, Reference) (model.ImplResponse, error)
	DeleteSubmodelReferenceAasRepository(context.Context, string, string) (model.ImplResponse, error)
	GetSubmodelByIdAasRepository(context.Context, string, string, string, string) (model.ImplResponse, error)
	PutSubmodelByIdAasRepository(context.Context, string, string, types.ISubmodel) (model.ImplResponse, error)
	DeleteSubmodelByIdAasRepository(context.Context, string, string) (model.ImplResponse, error)
	PatchSubmodelAasRepository(context.Context, string, string, types.ISubmodel, string) (model.ImplResponse, error)
	GetSubmodelByIdMetadataAasRepository(context.Context, string, string) (model.ImplResponse, error)
	PatchSubmodelByIdMetadataAasRepository(context.Context, string, string, SubmodelMetadata) (model.ImplResponse, error)
	GetSubmodelByIdValueOnlyAasRepository(context.Context, string, string, string, string) (model.ImplResponse, error)
	PatchSubmodelByIdValueOnlyAasRepository(context.Context, string, string, map[string]any, string) (model.ImplResponse, error)
	GetSubmodelByIdReferenceAasRepository(context.Context, string, string) (model.ImplResponse, error)
	GetSubmodelByIdPathAasRepository(context.Context, string, string, string) (model.ImplResponse, error)
	GetAllSubmodelElementsAasRepository(context.Context, string, string, int32, string, string, string) (model.ImplResponse, error)
	PostSubmodelElementAasRepository(context.Context, string, string, types.ISubmodelElement) (model.ImplResponse, error)
	GetAllSubmodelElementsMetadataAasRepository(context.Context, string, string, int32, string) (model.ImplResponse, error)
	GetAllSubmodelElementsValueOnlyAasRepository(context.Context, string, string, int32, string, string) (model.ImplResponse, error)
	GetAllSubmodelElementsReferenceAasRepository(context.Context, string, string, int32, string, string) (model.ImplResponse, error)
	GetAllSubmodelElementsPathAasRepository(context.Context, string, string, int32, string, string, string) (model.ImplResponse, error)
	GetSubmodelElementByPathAasRepository(context.Context, string, string, string, string, string) (model.ImplResponse, error)
	PutSubmodelElementByPathAasRepository(context.Context, string, string, string, types.ISubmodelElement) (model.ImplResponse, error)
	PostSubmodelElementByPathAasRepository(context.Context, string, string, string, types.ISubmodelElement) (model.ImplResponse, error)
	DeleteSubmodelElementByPathAasRepository(context.Context, string, string, string) (model.ImplResponse, error)
	PatchSubmodelElementValueByPathAasRepository(context.Context, string, string, string, types.ISubmodelElement, string) (model.ImplResponse, error)
	GetSubmodelElementByPathMetadataAasRepository(context.Context, string, string, string) (model.ImplResponse, error)
	PatchSubmodelElementValueByPathMetadata(context.Context, string, string, string, SubmodelElementMetadata) (model.ImplResponse, error)
	GetSubmodelElementByPathValueOnlyAasRepository(context.Context, string, string, string, string, string) (model.ImplResponse, error)
	PatchSubmodelElementValueByPathValueOnly(context.Context, string, string, string, SubmodelElementValue, string) (model.ImplResponse, error)
	GetSubmodelElementByPathReferenceAasRepository(context.Context, string, string, string, string) (model.ImplResponse, error)
	GetSubmodelElementByPathPathAasRepository(context.Context, string, string, string, string) (model.ImplResponse, error)
	GetFileByPathAasRepository(context.Context, string, string, string) (model.ImplResponse, error)
	PutFileByPathAasRepository(context.Context, string, string, string, string, *os.File) (model.ImplResponse, error)
	DeleteFileByPathAasRepository(context.Context, string, string, string) (model.ImplResponse, error)
	InvokeOperationAasRepository(context.Context, string, string, string, OperationRequest) (model.ImplResponse, error)
	InvokeOperationValueOnlyAasRepository(context.Context, string, string, string, OperationRequestValueOnly) (model.ImplResponse, error)
	InvokeOperationAsyncAasRepository(context.Context, string, string, string, OperationRequest) (model.ImplResponse, error)
	InvokeOperationAsyncValueOnlyAasRepository(context.Context, string, string, string, OperationRequestValueOnly) (model.ImplResponse, error)
	GetOperationAsyncStatusAasRepository(context.Context, string, string, string, string) (model.ImplResponse, error)
	GetOperationAsyncResultAasRepository(context.Context, string, string, string, string) (model.ImplResponse, error)
	GetOperationAsyncResultValueOnlyAasRepository(context.Context, string, string, string, string) (model.ImplResponse, error)
}

// DescriptionAPIAPIServicer defines the api actions for the DescriptionAPIAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DescriptionAPIAPIServicer interface {
	GetSelfDescription(context.Context) (model.ImplResponse, error)
}

// SerializationAPIAPIServicer defines the api actions for the SerializationAPIAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type SerializationAPIAPIServicer interface {
	GenerateSerializationByIds(context.Context, []string, []string, bool) (model.ImplResponse, error)
}
