// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"errors"
	"fmt"
	"strings"

	"github.com/aas-core-works/aas-core3.1-golang/jsonization"
	"github.com/aas-core-works/aas-core3.1-golang/types"
	"github.com/aas-core-works/aas-core3.1-golang/verification"
	jsoniter "github.com/json-iterator/go"
)

var allowedCompanyEndpointInterfaces = map[string]struct{}{
	"AAS-DISCOVERY-3.0":       {},
	"AAS-DISCOVERY-3.1":       {},
	"AAS-REGISTRY-3.0":        {},
	"AAS-REGISTRY-3.1":        {},
	"AAS-REPOSITORY-3.0":      {},
	"AAS-REPOSITORY-3.1":      {},
	"SUBMODEL-REGISTRY-3.0":   {},
	"SUBMODEL-REGISTRY-3.1":   {},
	"SUBMODEL-REPOSITORY-3.0": {},
	"SUBMODEL-REPOSITORY-3.1": {},
	"AASX-FILE-3.0":           {},
	"AASX-FILE-3.1":           {},
	"MQTT-BROKER-3.1.1":       {},
}

var requiredCoreCompanyEndpointInterfaces = map[string]struct{}{
	"AAS-DISCOVERY-3.0":       {},
	"AAS-DISCOVERY-3.1":       {},
	"AAS-REGISTRY-3.0":        {},
	"AAS-REGISTRY-3.1":        {},
	"AAS-REPOSITORY-3.0":      {},
	"AAS-REPOSITORY-3.1":      {},
	"SUBMODEL-REGISTRY-3.0":   {},
	"SUBMODEL-REGISTRY-3.1":   {},
	"SUBMODEL-REPOSITORY-3.0": {},
	"SUBMODEL-REPOSITORY-3.1": {},
	"AASX-FILE-3.0":           {},
	"AASX-FILE-3.1":           {},
}

// CompanyEndpointInterfaceConstraintError indicates that endpoint interface
// values violate the company descriptor interface policy.
type CompanyEndpointInterfaceConstraintError struct {
	Message string
}

func (e *CompanyEndpointInterfaceConstraintError) Error() string {
	return e.Message
}

// IsCompanyEndpointInterfaceConstraintError reports whether err is caused by
// invalid endpoint interface values or a missing required core interface.
func IsCompanyEndpointInterfaceConstraintError(err error) bool {
	var target *CompanyEndpointInterfaceConstraintError
	return errors.As(err, &target)
}

func validateCompanyEndpointInterfaces(endpoints []Endpoint) error {
	hasRequiredCoreInterface := false

	for i, el := range endpoints {
		interfaceName := strings.TrimSpace(el.Interface)

		if _, ok := allowedCompanyEndpointInterfaces[interfaceName]; !ok {
			return &CompanyEndpointInterfaceConstraintError{
				Message: fmt.Sprintf("endpoints[%d].interface %q is not allowed", i, el.Interface),
			}
		}

		if _, ok := requiredCoreCompanyEndpointInterfaces[interfaceName]; ok {
			hasRequiredCoreInterface = true
		}
	}

	if !hasRequiredCoreInterface {
		return &CompanyEndpointInterfaceConstraintError{
			Message: "endpoints must contain at least one required core interface",
		}
	}

	return nil
}

func IsStrictCompanyDomain(domain string) bool {
	domain = strings.TrimSpace(domain)
	if domain == "" || strings.HasPrefix(domain, ".") || strings.HasSuffix(domain, ".") {
		return false
	}
	if len(domain) > 253 {
		return false
	}

	labels := strings.Split(domain, ".")
	if len(labels) < 2 {
		return false
	}

	for _, label := range labels {
		if !isValidCompanyDomainLabel(label) {
			return false
		}
	}

	for _, char := range labels[len(labels)-1] {
		if (char < 'a' || char > 'z') && (char < 'A' || char > 'Z') {
			return false
		}
	}

	return true
}

func isValidCompanyDomainLabel(label string) bool {
	if len(label) == 0 || len(label) > 63 {
		return false
	}
	if label[0] == '-' || label[len(label)-1] == '-' {
		return false
	}

	for _, char := range label {
		isUpper := char >= 'A' && char <= 'Z'
		isLower := char >= 'a' && char <= 'z'
		isDigit := char >= '0' && char <= '9'
		if !isUpper && !isLower && !isDigit && char != '-' {
			return false
		}
	}

	return true
}

type CompanyDescriptor struct {
	Description []types.ILangStringTextType `json:"description,omitempty"`

	DisplayName []types.ILangStringNameType `json:"displayName,omitempty"`

	Administration types.IAdministrativeInformation `json:"administration,omitempty"`

	Endpoints []Endpoint `json:"endpoints,omitempty"`

	GlobalAssetId string `json:"globalAssetId,omitempty" validate:"regexp=^([\\\\x09\\\\x0a\\\\x0d\\\\x20-\\\\ud7ff\\\\ue000-\\\\ufffd]|\\\\ud800[\\\\udc00-\\\\udfff]|[\\\\ud801-\\\\udbfe][\\\\udc00-\\\\udfff]|\\\\udbff[\\\\udc00-\\\\udfff])*$"`

	IdShort string `json:"idShort,omitempty" validate:"regexp=^[a-zA-Z][a-zA-Z0-9_-]*[a-zA-Z0-9_]+$"`

	Name string `json:"name,omitempty" validate:"regexp=^[A-Za-z0-9 ._-]*$"`

	Domain string `json:"domain,omitempty" validate:"regexp=^[A-Za-z0-9.-]*$"`

	NameOptions []string `json:"nameOptions,omitempty"`

	AssetIdRegexPatterns []string `json:"assetIdRegexPatterns,omitempty"`
}

// AssertCompanyDescriptorRequired checks if the required fields are not zero-ed
func AssertCompanyDescriptorRequired(obj CompanyDescriptor) error {
	if strings.TrimSpace(obj.Domain) == "" {
		return &RequiredError{Field: "domain"}
	}
	if strings.TrimSpace(obj.Name) == "" {
		return &RequiredError{Field: "name"}
	}
	if len(obj.Endpoints) == 0 {
		return &RequiredError{Field: "endpoints"}
	}
	for _, el := range obj.Endpoints {
		if err := AssertEndpointRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCompanyDescriptorConstraints checks if the values respects the defined constraints
func AssertCompanyDescriptorConstraints(obj CompanyDescriptor) error {
	if strings.TrimSpace(obj.Domain) != "" && !IsStrictCompanyDomain(obj.Domain) {
		return fmt.Errorf("domain %q is not a syntactically valid domain", obj.Domain)
	}

	for _, el := range obj.Endpoints {
		if err := AssertEndpointConstraints(el); err != nil {
			return err
		}
	}

	if err := validateCompanyEndpointInterfaces(obj.Endpoints); err != nil {
		return err
	}

	seen := make(map[string]struct{}, len(obj.NameOptions))
	for i, option := range obj.NameOptions {
		if option == "" {
			return fmt.Errorf("nameOptions[%d] must not be empty", i)
		}
		if _, ok := seen[option]; ok {
			return fmt.Errorf("nameOptions contains duplicate value %q", option)
		}
		seen[option] = struct{}{}
	}

	assetRegexSeen := make(map[string]struct{}, len(obj.AssetIdRegexPatterns))
	for i, pattern := range obj.AssetIdRegexPatterns {
		if pattern == "" {
			return fmt.Errorf("assetIdRegexPatterns[%d] must not be empty", i)
		}
		if _, ok := assetRegexSeen[pattern]; ok {
			return fmt.Errorf("assetIdRegexPatterns contains duplicate value %q", pattern)
		}
		assetRegexSeen[pattern] = struct{}{}
	}
	return nil
}

func (obj CompanyDescriptor) ToJsonable() (map[string]any, error) {
	// Marshal every AAS GO SDK Type
	ret := make(map[string]any)
	// Description
	var descriptions []map[string]any
	for _, desc := range obj.Description {
		desc, err := jsonization.ToJsonable(desc)
		if err != nil {
			return nil, err
		}
		descriptions = append(descriptions, desc)
	}

	// Display Name
	var displayNames []map[string]any
	for _, dn := range obj.DisplayName {
		dn, err := jsonization.ToJsonable(dn)
		if err != nil {
			return nil, err
		}
		displayNames = append(displayNames, dn)
	}

	// Administration
	var administration map[string]any
	if obj.Administration != nil {
		var err error
		administration, err = jsonization.ToJsonable(obj.Administration)
		if err != nil {
			return nil, err
		}
	}

	if len(descriptions) > 0 {
		ret["description"] = descriptions
	}
	if len(displayNames) > 0 {
		ret["displayName"] = displayNames
	}
	if administration != nil {
		ret["administration"] = administration
	}
	if len(obj.Endpoints) > 0 {
		ret["endpoints"] = obj.Endpoints
	}
	if obj.IdShort != "" {
		ret["idShort"] = obj.IdShort
	}
	if obj.Name != "" {
		ret["name"] = obj.Name
	}
	if obj.Domain != "" {
		ret["domain"] = obj.Domain
	}
	if len(obj.NameOptions) > 0 {
		ret["nameOptions"] = obj.NameOptions
	}
	if len(obj.AssetIdRegexPatterns) > 0 {
		ret["assetIdRegexPatterns"] = obj.AssetIdRegexPatterns
	}
	return ret, nil
}

// UnmarshalJSON implements custom unmarshaling for SubmodelDescriptor
// It handles the FromJsonable Unmarshalling of the aas-go-sdk types
func (obj *CompanyDescriptor) UnmarshalJSON(data []byte) error {
	var json = jsoniter.ConfigCompatibleWithStandardLibrary
	var jsonable map[string]any
	if err := json.Unmarshal(data, &jsonable); err != nil {
		return err
	}

	// Check for unknown fields
	allowedFields := map[string]bool{
		"administration":       true,
		"endpoints":            true,
		"idShort":              true,
		"name":                 true,
		"domain":               true,
		"nameOptions":          true,
		"assetIdRegexPatterns": true,
		"idLinkRegexPatterns":  true,
		"description":          true,
		"displayName":          true,
		"extensions":           true,
	}
	for key := range jsonable {
		if !allowedFields[key] {
			return errors.New("unknown field: " + key)
		}
	}

	// Description
	if descs, ok := jsonable["description"].([]any); ok {
		for _, desc := range descs {
			descMap, ok := desc.(map[string]any)
			if !ok {
				return errors.New("CompanyDescriptor: description is not a map")
			}
			var langString types.ILangStringTextType
			langString, err := jsonization.LangStringTextTypeFromJsonable(descMap)
			if err != nil {
				return err
			}
			obj.Description = append(obj.Description, langString)
		}
	}

	// Display Name
	if dns, ok := jsonable["displayName"].([]any); ok {
		for _, dn := range dns {
			dnMap, ok := dn.(map[string]any)
			if !ok {
				return errors.New("CompanyDescriptor: displayName is not a map")
			}
			var langString types.ILangStringNameType
			langString, err := jsonization.LangStringNameTypeFromJsonable(dnMap)
			if err != nil {
				return err
			}
			obj.DisplayName = append(obj.DisplayName, langString)
		}
	}

	// Endpoints
	if eps, ok := jsonable["endpoints"].([]any); ok {
		for _, ep := range eps {
			epMap, ok := ep.(map[string]any)
			if !ok {
				return errors.New("CompanyDescriptor: endpoint is not a map")
			}
			var endpoint Endpoint
			endpointBytes, err := json.Marshal(epMap)
			if err != nil {
				return err
			}
			if err := json.Unmarshal(endpointBytes, &endpoint); err != nil {
				return err
			}
			obj.Endpoints = append(obj.Endpoints, endpoint)
		}
	}

	// Administration
	if admin, ok := jsonable["administration"].(map[string]any); ok {
		var administration types.IAdministrativeInformation
		administration, err := jsonization.AdministrativeInformationFromJsonable(admin)
		if err != nil {
			return err
		}
		obj.Administration = administration
	}

	// Handle other simple fields
	if idShort, ok := jsonable["idShort"].(string); ok {
		obj.IdShort = idShort
	}
	if name, ok := jsonable["name"].(string); ok {
		obj.Name = name
	}
	if domain, ok := jsonable["domain"].(string); ok {
		obj.Domain = domain
	}
	if options, ok := jsonable["nameOptions"].([]any); ok {
		for i, rawOption := range options {
			option, ok := rawOption.(string)
			if !ok {
				return fmt.Errorf("CompanyDescriptor: nameOptions[%d] is not a string", i)
			}
			obj.NameOptions = append(obj.NameOptions, option)
		}
	}
	if patterns, ok := jsonable["assetIdRegexPatterns"].([]any); ok {
		for i, rawPattern := range patterns {
			pattern, ok := rawPattern.(string)
			if !ok {
				return fmt.Errorf("CompanyDescriptor: assetIdRegexPatterns[%d] is not a string", i)
			}
			obj.AssetIdRegexPatterns = append(obj.AssetIdRegexPatterns, pattern)
		}
	}

	// Verify Description
	var validationErrors []string
	for _, el := range obj.Description {
		verification.Verify(el, func(verErr *verification.VerificationError) bool {
			validationErrors = append(validationErrors, verErr.Error())
			return false // Continue collecting all errors
		})

		if len(validationErrors) > 0 {
			return errors.New("CompanyDescriptor: Description verification failed: " + validationErrors[0])
		}
	}

	// Verify DisplayName
	validationErrors = []string{}
	for _, el := range obj.DisplayName {
		verification.Verify(el, func(verErr *verification.VerificationError) bool {
			validationErrors = append(validationErrors, verErr.Error())
			return false // Continue collecting all errors
		})

		if len(validationErrors) > 0 {
			return errors.New("CompanyDescriptor: DisplayName verification failed: " + validationErrors[0])
		}
	}

	// Administration
	validationErrors = []string{}
	if obj.Administration != nil {
		verification.Verify(obj.Administration, func(verErr *verification.VerificationError) bool {
			validationErrors = append(validationErrors, verErr.Error())
			return false // Continue collecting all errors
		})
		if len(validationErrors) > 0 {
			return errors.New("CompanyDescriptor: Administration verification failed: " + validationErrors[0])
		}
	}

	return nil
}
