// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository Service Specification
 *
 * The Full Profile of the Asset Administration Shell Repository Service Specification as part of the [Specification of the Asset Administration Shell: Part 2](https://industrialdigitaltwin.org/en/content-hub/aasspecifications).   Copyright: Industrial Digital Twin Association (IDTA) 2025
 *
 * API version: V3.1.1_SSP-001
 * Contact: info@idtwin.org
 */

// package openapi
package api

import (
	"context"
	"errors"
	"net/http"
	"os"
	"strings"

	"github.com/aas-core-works/aas-core3.1-golang/jsonization"
	"github.com/aas-core-works/aas-core3.1-golang/types"
	persistencepostgresql "github.com/eclipse-basyx/basyx-go-components/internal/aasrepository/persistence"
	"github.com/eclipse-basyx/basyx-go-components/internal/common"
	gen "github.com/eclipse-basyx/basyx-go-components/internal/common/model"
	openapi "github.com/eclipse-basyx/basyx-go-components/pkg/aasrepositoryapi/go"
)

// AssetAdministrationShellRepositoryAPIAPIService is a service that implements the logic for the AssetAdministrationShellRepositoryAPIAPIServicer
// This service should implement the business logic for every endpoint for the AssetAdministrationShellRepositoryAPIAPI API.
// Include any external packages or services that will be required by this service.
type AssetAdministrationShellRepositoryAPIAPIService struct {
	assetAdministrationShellBackend persistencepostgresql.AssetAdministrationShellDatabase
}

const componentName = "AASREPO"

// NewAssetAdministrationShellRepositoryAPIAPIService creates a default api service
func NewAssetAdministrationShellRepositoryAPIAPIService(databaseBackendAssetAdministrationShell persistencepostgresql.AssetAdministrationShellDatabase) *AssetAdministrationShellRepositoryAPIAPIService {
	return &AssetAdministrationShellRepositoryAPIAPIService{
		assetAdministrationShellBackend: databaseBackendAssetAdministrationShell,
	}
}

func newAPIErrorResponse(err error, status int, operation string, info string) gen.ImplResponse {
	if err == nil {
		err = errors.New(http.StatusText(status))
	}

	return common.NewErrorResponse(err, status, componentName, operation, info)
}

// GetAllAssetAdministrationShells - Returns all Asset Administration Shells
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetAllAssetAdministrationShells(ctx context.Context, assetIds []string, idShort string, limit int32, cursor string) (gen.ImplResponse, error) {

	const operation = "GetAllAssetAdministrationShells"

	decodedCursor, decodeErr := common.DecodeString(cursor)
	if decodeErr != nil {
		return newAPIErrorResponse(decodeErr, http.StatusBadRequest, operation, "BadCursor"), nil
	}

	aasList, nextCursor, err := s.assetAdministrationShellBackend.GetAssetAdministrationShells(ctx, limit, decodedCursor, idShort, assetIds)
	if err != nil {
		if common.IsErrBadRequest(err) {
			return newAPIErrorResponse(err, http.StatusBadRequest, operation, "BadRequest"), nil
		}
		return newAPIErrorResponse(err, http.StatusInternalServerError, operation, "GetAssetAdministrationShells"), err
	}

	return gen.Response(http.StatusOK, gen.GetAssetAdministrationShellsResult{
		PagingMetadata: gen.PagedResultPagingMetadata{Cursor: common.EncodeString(nextCursor)},
		Result:         aasList,
	}), nil
}

// PostAssetAdministrationShell - Creates a new Asset Administration Shell
func (s *AssetAdministrationShellRepositoryAPIAPIService) PostAssetAdministrationShell(ctx context.Context, aas types.IAssetAdministrationShell) (gen.ImplResponse, error) {
	const operation = "PostAssetAdministrationShell"

	err := s.assetAdministrationShellBackend.CreateAssetAdministrationShell(ctx, aas)

	if err != nil {
		if common.IsErrDenied(err) {
			return newAPIErrorResponse(err, http.StatusForbidden, operation, "Forbidden"), nil
		}
		if common.IsErrConflict(err) {
			return newAPIErrorResponse(err, http.StatusConflict, operation, "IdConflict"), nil
		}

		if common.IsErrBadRequest(err) {
			return newAPIErrorResponse(err, http.StatusBadRequest, operation, "InvalidAssetAdministrationShellData"), nil
		}

		return newAPIErrorResponse(err, http.StatusInternalServerError, operation, "CreateAssetAdministrationShell"), err
	}

	aasJsonable, err := jsonization.ToJsonable(aas)
	if err != nil {
		return newAPIErrorResponse(err, http.StatusBadRequest, operation, "InvalidAssetAdministrationShellData"), nil
	}

	return gen.Response(http.StatusCreated, aasJsonable), nil
}

// GetAllAssetAdministrationShellsReference - Returns References to all Asset Administration Shells
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetAllAssetAdministrationShellsReference(ctx context.Context, assetIds []string, idShort string, limit int32, cursor string) (gen.ImplResponse, error) {

	const operation = "GetAllAssetAdministrationShellsReference"

	decodedCursor, decodeErr := common.DecodeString(cursor)
	if decodeErr != nil {
		return newAPIErrorResponse(decodeErr, http.StatusBadRequest, operation, "BadCursor"), nil
	}

	references, nextCursor, err := s.assetAdministrationShellBackend.GetAssetAdministrationShellReferences(ctx, limit, decodedCursor, idShort, assetIds)
	if err != nil {
		if common.IsErrBadRequest(err) {
			return newAPIErrorResponse(err, http.StatusBadRequest, operation, "BadRequest"), nil
		}
		return newAPIErrorResponse(err, http.StatusInternalServerError, operation, "GetAssetAdministrationShellReferences"), err
	}

	jsonReferences := make([]map[string]any, 0, len(references))
	for _, reference := range references {
		jsonReference, jsonErr := jsonization.ToJsonable(reference)
		if jsonErr != nil {
			return newAPIErrorResponse(jsonErr, http.StatusInternalServerError, operation, "ToJsonable"), jsonErr
		}
		jsonReferences = append(jsonReferences, jsonReference)
	}

	return gen.Response(http.StatusOK, gen.GetReferencesResult{
		PagingMetadata: gen.PagedResultPagingMetadata{Cursor: common.EncodeString(nextCursor)},
		Result:         jsonReferences,
	}), nil
}

// GetAssetAdministrationShellById - Returns a specific Asset Administration Shell
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetAssetAdministrationShellById(ctx context.Context, aasIdentifier string) (gen.ImplResponse, error) {

	const operation = "GetAssetAdministrationShellById"

	decodedIdentifier, decodeErr := common.DecodeString(aasIdentifier)
	if decodeErr != nil {
		return newAPIErrorResponse(decodeErr, http.StatusBadRequest, operation, "MalformedAssetAdministrationShellIdentifier"), nil
	}

	aasMap, err := s.assetAdministrationShellBackend.GetAssetAdministrationShellByID(ctx, decodedIdentifier)
	if err != nil {
		if common.IsErrNotFound(err) {
			return newAPIErrorResponse(err, http.StatusNotFound, operation, "AssetAdministrationShellNotFound"), nil
		}
		return newAPIErrorResponse(err, http.StatusInternalServerError, operation, "GetAssetAdministrationShellByID"), err
	}

	return gen.Response(http.StatusOK, aasMap), nil
}

// PutAssetAdministrationShellById - Creates or updates an existing Asset Administration Shell
func (s *AssetAdministrationShellRepositoryAPIAPIService) PutAssetAdministrationShellById(ctx context.Context, aasIdentifier string, assetAdministrationShell types.IAssetAdministrationShell) (gen.ImplResponse, error) {

	const operation = "PutAssetAdministrationShellById"

	decodedIdentifier, decodeErr := common.DecodeString(aasIdentifier)
	if decodeErr != nil {
		return newAPIErrorResponse(decodeErr, http.StatusBadRequest, operation, "MalformedAssetAdministrationShellIdentifier"), nil
	}

	isUpdate, putErr := s.assetAdministrationShellBackend.PutAssetAdministrationShellByID(ctx, decodedIdentifier, assetAdministrationShell)
	if putErr != nil {
		if common.IsErrDenied(putErr) {
			return newAPIErrorResponse(putErr, http.StatusForbidden, operation, "Forbidden"), nil
		}
		if common.IsErrBadRequest(putErr) {
			return newAPIErrorResponse(putErr, http.StatusBadRequest, operation, "BadRequest"), nil
		}
		if common.IsErrConflict(putErr) {
			return newAPIErrorResponse(putErr, http.StatusConflict, operation, "Conflict"), nil
		}
		return newAPIErrorResponse(putErr, http.StatusInternalServerError, operation, "PutAssetAdministrationShellByID"), putErr
	}

	if isUpdate {
		return gen.Response(http.StatusNoContent, nil), nil
	}

	jsonableAAS, err := jsonization.ToJsonable(assetAdministrationShell)
	if err != nil {
		return newAPIErrorResponse(err, http.StatusBadRequest, operation, "InvalidAssetAdministrationShellData"), nil
	}

	return gen.Response(http.StatusCreated, jsonableAAS), nil
}

// DeleteAssetAdministrationShellById - Deletes an Asset Administration Shell
func (s *AssetAdministrationShellRepositoryAPIAPIService) DeleteAssetAdministrationShellById(ctx context.Context, aasIdentifier string) (gen.ImplResponse, error) {

	const operation = "DeleteAssetAdministrationShellById"

	decodedIdentifier, decodeErr := common.DecodeString(aasIdentifier)
	if decodeErr != nil {
		return newAPIErrorResponse(decodeErr, http.StatusBadRequest, operation, "MalformedAssetAdministrationShellIdentifier"), nil
	}

	err := s.assetAdministrationShellBackend.DeleteAssetAdministrationShellByID(ctx, decodedIdentifier)
	if err != nil {
		if common.IsErrDenied(err) {
			return newAPIErrorResponse(err, http.StatusForbidden, operation, "Forbidden"), nil
		}
		if common.IsErrNotFound(err) {
			return newAPIErrorResponse(err, http.StatusNotFound, operation, "AssetAdministrationShellNotFound"), nil
		}
		return newAPIErrorResponse(err, http.StatusInternalServerError, operation, "DeleteAssetAdministrationShellByID"), err
	}

	return gen.Response(http.StatusNoContent, nil), nil
}

// GetAssetAdministrationShellByIdReferenceAasRepository - Returns a specific Asset Administration Shell as a Reference
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetAssetAdministrationShellByIdReferenceAasRepository(ctx context.Context, aasIdentifier string) (gen.ImplResponse, error) {

	const operation = "GetAssetAdministrationShellByIdReferenceAasRepository"

	decodedIdentifier, decodeErr := common.DecodeString(aasIdentifier)
	if decodeErr != nil {
		return newAPIErrorResponse(decodeErr, http.StatusBadRequest, operation, "MalformedAssetAdministrationShellIdentifier"), nil
	}

	reference, err := s.assetAdministrationShellBackend.GetAssetAdministrationShellReferenceByID(ctx, decodedIdentifier)
	if err != nil {
		if common.IsErrNotFound(err) {
			return newAPIErrorResponse(err, http.StatusNotFound, operation, "AssetAdministrationShellNotFound"), nil
		}
		return newAPIErrorResponse(err, http.StatusInternalServerError, operation, "GetAssetAdministrationShellReferenceByID"), err
	}

	jsonReference, jsonErr := jsonization.ToJsonable(reference)
	if jsonErr != nil {
		return newAPIErrorResponse(jsonErr, http.StatusInternalServerError, operation, "ToJsonable"), jsonErr
	}

	return gen.Response(http.StatusOK, jsonReference), nil
}

// GetAssetInformationAasRepository - Returns the Asset Information
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetAssetInformationAasRepository(ctx context.Context, aasIdentifier string) (gen.ImplResponse, error) {

	const operation = "GetAssetInformationAasRepository"

	decodedIdentifier, decodeErr := common.DecodeString(aasIdentifier)
	if decodeErr != nil {
		return newAPIErrorResponse(decodeErr, http.StatusBadRequest, operation, "MalformedAssetAdministrationShellIdentifier"), nil
	}

	assetInformation, err := s.assetAdministrationShellBackend.GetAssetInformationByAASID(ctx, decodedIdentifier)
	if err != nil {
		if common.IsErrNotFound(err) {
			return newAPIErrorResponse(err, http.StatusNotFound, operation, "AssetAdministrationShellNotFound"), nil
		}
		return newAPIErrorResponse(err, http.StatusInternalServerError, operation, "GetAssetInformationByAASID"), err
	}

	return gen.Response(http.StatusOK, assetInformation), nil
}

// PutAssetInformationAasRepository - Updates the Asset Information
func (s *AssetAdministrationShellRepositoryAPIAPIService) PutAssetInformationAasRepository(ctx context.Context, aasIdentifier string, assetInformation types.IAssetInformation) (gen.ImplResponse, error) {

	const operation = "PutAssetInformationAasRepository"

	decodedIdentifier, decodeErr := common.DecodeString(aasIdentifier)
	if decodeErr != nil {
		return newAPIErrorResponse(decodeErr, http.StatusBadRequest, operation, "MalformedAssetAdministrationShellIdentifier"), nil
	}

	err := s.assetAdministrationShellBackend.PutAssetInformationByAASID(ctx, decodedIdentifier, assetInformation)
	if err != nil {
		if common.IsErrDenied(err) {
			return newAPIErrorResponse(err, http.StatusForbidden, operation, "Forbidden"), nil
		}
		if common.IsErrNotFound(err) {
			return newAPIErrorResponse(err, http.StatusNotFound, operation, "AssetAdministrationShellNotFound"), nil
		}
		if common.IsErrBadRequest(err) {
			return newAPIErrorResponse(err, http.StatusBadRequest, operation, "BadRequest"), nil
		}
		return newAPIErrorResponse(err, http.StatusInternalServerError, operation, "PutAssetInformationByAASID"), err
	}

	return gen.Response(http.StatusNoContent, nil), nil
}

// GetThumbnailAasRepository -
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetThumbnailAasRepository(ctx context.Context, aasIdentifier string) (gen.ImplResponse, error) {

	const operation = "GetThumbnailAasRepository"

	decodedIdentifier, decodeErr := common.DecodeString(aasIdentifier)
	if decodeErr != nil {
		return newAPIErrorResponse(decodeErr, http.StatusBadRequest, operation, "MalformedAssetAdministrationShellIdentifier"), nil
	}

	fileContent, contentType, fileName, thumbnailPath, err := s.assetAdministrationShellBackend.GetThumbnailByAASID(ctx, decodedIdentifier)
	if err != nil {
		if common.IsErrNotFound(err) {
			return newAPIErrorResponse(err, http.StatusNotFound, operation, "ThumbnailNotFound"), nil
		}
		if common.IsErrBadRequest(err) {
			return newAPIErrorResponse(err, http.StatusBadRequest, operation, "BadRequest"), nil
		}
		return newAPIErrorResponse(err, http.StatusInternalServerError, operation, "GetThumbnailByAASID"), err
	}

	if strings.HasPrefix(thumbnailPath, "http://") || strings.HasPrefix(thumbnailPath, "https://") {
		return gen.Response(http.StatusFound, openapi.Redirect{Location: thumbnailPath}), nil
	}

	resolvedContentType := strings.TrimSpace(contentType)
	if resolvedContentType == "" {
		if len(fileContent) > 0 {
			resolvedContentType = http.DetectContentType(fileContent)
		} else {
			resolvedContentType = "application/octet-stream"
		}
	}

	return gen.Response(http.StatusOK, openapi.FileDownload{
		Content:     fileContent,
		ContentType: resolvedContentType,
		Filename:    fileName,
	}), nil
}

// PutThumbnailAasRepository -
func (s *AssetAdministrationShellRepositoryAPIAPIService) PutThumbnailAasRepository(ctx context.Context, aasIdentifier string, fileName string, file *os.File) (gen.ImplResponse, error) {

	const operation = "PutThumbnailAasRepository"

	decodedIdentifier, decodeErr := common.DecodeString(aasIdentifier)
	if decodeErr != nil {
		return newAPIErrorResponse(decodeErr, http.StatusBadRequest, operation, "MalformedAssetAdministrationShellIdentifier"), nil
	}

	err := s.assetAdministrationShellBackend.PutThumbnailByAASID(ctx, decodedIdentifier, fileName, file)
	if err != nil {
		if common.IsErrDenied(err) {
			return newAPIErrorResponse(err, http.StatusForbidden, operation, "Forbidden"), nil
		}
		if common.IsErrNotFound(err) {
			return newAPIErrorResponse(err, http.StatusNotFound, operation, "AssetAdministrationShellNotFound"), nil
		}
		if common.IsErrBadRequest(err) {
			return newAPIErrorResponse(err, http.StatusBadRequest, operation, "BadRequest"), nil
		}
		return newAPIErrorResponse(err, http.StatusInternalServerError, operation, "PutThumbnailByAASID"), err
	}

	return gen.Response(http.StatusNoContent, nil), nil
}

// DeleteThumbnailAasRepository -
func (s *AssetAdministrationShellRepositoryAPIAPIService) DeleteThumbnailAasRepository(ctx context.Context, aasIdentifier string) (gen.ImplResponse, error) {

	const operation = "DeleteThumbnailAasRepository"

	decodedIdentifier, decodeErr := common.DecodeString(aasIdentifier)
	if decodeErr != nil {
		return newAPIErrorResponse(decodeErr, http.StatusBadRequest, operation, "MalformedAssetAdministrationShellIdentifier"), nil
	}

	err := s.assetAdministrationShellBackend.DeleteThumbnailByAASID(ctx, decodedIdentifier)
	if err != nil {
		if common.IsErrDenied(err) {
			return newAPIErrorResponse(err, http.StatusForbidden, operation, "Forbidden"), nil
		}
		if common.IsErrNotFound(err) {
			return newAPIErrorResponse(err, http.StatusNotFound, operation, "ThumbnailNotFound"), nil
		}
		if common.IsErrBadRequest(err) {
			return newAPIErrorResponse(err, http.StatusBadRequest, operation, "BadRequest"), nil
		}
		return newAPIErrorResponse(err, http.StatusInternalServerError, operation, "DeleteThumbnailByAASID"), err
	}

	return gen.Response(http.StatusNoContent, nil), nil
}

// GetAllSubmodelReferencesAasRepository - Returns all submodel references
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetAllSubmodelReferencesAasRepository(ctx context.Context, aasIdentifier string, limit int32, cursor string) (gen.ImplResponse, error) {

	const operation = "GetAllSubmodelReferencesAasRepository"

	decodedIdentifier, decodeErr := common.DecodeString(aasIdentifier)
	if decodeErr != nil {
		return newAPIErrorResponse(decodeErr, http.StatusBadRequest, operation, "MalformedAssetAdministrationShellIdentifier"), nil
	}

	decodedCursor, cursorDecodeErr := common.DecodeString(cursor)
	if cursorDecodeErr != nil {
		return newAPIErrorResponse(cursorDecodeErr, http.StatusBadRequest, operation, "BadCursor"), nil
	}

	references, nextCursor, err := s.assetAdministrationShellBackend.GetAllSubmodelReferencesByAASID(ctx, decodedIdentifier, limit, decodedCursor)
	if err != nil {
		if common.IsErrNotFound(err) {
			return newAPIErrorResponse(err, http.StatusNotFound, operation, "AssetAdministrationShellNotFound"), nil
		}
		if common.IsErrBadRequest(err) {
			return newAPIErrorResponse(err, http.StatusBadRequest, operation, "BadRequest"), nil
		}
		return newAPIErrorResponse(err, http.StatusInternalServerError, operation, "GetAllSubmodelReferencesByAASID"), err
	}

	jsonReferences := make([]map[string]any, 0, len(references))
	for _, reference := range references {
		jsonReference, jsonErr := jsonization.ToJsonable(reference)
		if jsonErr != nil {
			return newAPIErrorResponse(jsonErr, http.StatusInternalServerError, operation, "ToJsonable"), jsonErr
		}
		jsonReferences = append(jsonReferences, jsonReference)
	}

	return gen.Response(http.StatusOK, gen.GetReferencesResult{
		PagingMetadata: gen.PagedResultPagingMetadata{Cursor: common.EncodeString(nextCursor)},
		Result:         jsonReferences,
	}), nil
}

// PostSubmodelReferenceAasRepository - Creates a submodel reference at the Asset Administration Shell
func (s *AssetAdministrationShellRepositoryAPIAPIService) PostSubmodelReferenceAasRepository(ctx context.Context, aasIdentifier string, reference types.IReference) (gen.ImplResponse, error) {
	const operation = "PostSubmodelReferenceAasRepository"

	decodedAssetAdministrationShellIdentifier, decodeErr := common.DecodeString(aasIdentifier)
	if decodeErr != nil {
		return newAPIErrorResponse(decodeErr, http.StatusBadRequest, operation, "MalformedAssetAdministrationShellIdentifier"), nil
	}

	if err := s.assetAdministrationShellBackend.CreateSubmodelReferenceInAssetAdministrationShell(ctx, decodedAssetAdministrationShellIdentifier, reference); err != nil {
		if common.IsErrDenied(err) {
			return newAPIErrorResponse(err, http.StatusForbidden, operation, "Forbidden"), nil
		}
		if common.IsErrNotFound(err) {
			return newAPIErrorResponse(err, http.StatusNotFound, operation, "AssetAdministrationShellNotFound"), nil
		}
		if common.IsErrConflict(err) {
			return newAPIErrorResponse(err, http.StatusConflict, operation, "Conflict"), nil
		}
		if common.IsErrBadRequest(err) {
			return newAPIErrorResponse(err, http.StatusBadRequest, operation, "BadRequest"), nil
		}
		return newAPIErrorResponse(err, http.StatusInternalServerError, operation, "CreateSubmodelReferenceInAssetAdministrationShell"), err
	}

	referenceJsonable, err := jsonization.ToJsonable(reference)
	if err != nil {
		return newAPIErrorResponse(err, http.StatusBadRequest, operation, "InvalidReferenceData"), nil
	}

	return gen.Response(http.StatusCreated, referenceJsonable), nil
}

// DeleteSubmodelReferenceAasRepository - Deletes the submodel reference from the Asset Administration Shell. Does not delete the submodel itself.
func (s *AssetAdministrationShellRepositoryAPIAPIService) DeleteSubmodelReferenceAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string) (gen.ImplResponse, error) {

	const operation = "DeleteSubmodelReferenceAasRepository"

	decodedAASIdentifier, decodeAASErr := common.DecodeString(aasIdentifier)
	if decodeAASErr != nil {
		return newAPIErrorResponse(decodeAASErr, http.StatusBadRequest, operation, "MalformedAssetAdministrationShellIdentifier"), nil
	}

	decodedSubmodelIdentifier, decodeSubmodelErr := common.DecodeString(submodelIdentifier)
	if decodeSubmodelErr != nil {
		return newAPIErrorResponse(decodeSubmodelErr, http.StatusBadRequest, operation, "MalformedSubmodelIdentifier"), nil
	}

	err := s.assetAdministrationShellBackend.DeleteSubmodelReferenceInAssetAdministrationShell(ctx, decodedAASIdentifier, decodedSubmodelIdentifier)
	if err != nil {
		if common.IsErrDenied(err) {
			return newAPIErrorResponse(err, http.StatusForbidden, operation, "Forbidden"), nil
		}
		if common.IsErrNotFound(err) {
			return newAPIErrorResponse(err, http.StatusNotFound, operation, "SubmodelReferenceNotFound"), nil
		}
		if common.IsErrBadRequest(err) {
			return newAPIErrorResponse(err, http.StatusBadRequest, operation, "BadRequest"), nil
		}
		return newAPIErrorResponse(err, http.StatusInternalServerError, operation, "DeleteSubmodelReferenceInAssetAdministrationShell"), err
	}

	return gen.Response(http.StatusNoContent, nil), nil
}

// GetSubmodelByIdAasRepository - Returns the Submodel
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetSubmodelByIdAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, level string, extent string) (gen.ImplResponse, error) {
	return gen.Response(http.StatusNotImplemented, nil), errors.New("GetSubmodelByIdAasRepository method not implemented")
}

// PutSubmodelByIdAasRepository - Creates or updates the Submodel
func (s *AssetAdministrationShellRepositoryAPIAPIService) PutSubmodelByIdAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, submodel types.ISubmodel) (gen.ImplResponse, error) {
	return gen.Response(http.StatusNotImplemented, nil), errors.New("PutSubmodelByIdAasRepository method not implemented")
}

// DeleteSubmodelByIdAasRepository - Deletes the submodel from the Asset Administration Shell and the Repository.
func (s *AssetAdministrationShellRepositoryAPIAPIService) DeleteSubmodelByIdAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string) (gen.ImplResponse, error) {
	return gen.Response(http.StatusNotImplemented, nil), errors.New("DeleteSubmodelByIdAasRepository method not implemented")
}

// PatchSubmodelAasRepository - Updates the Submodel
func (s *AssetAdministrationShellRepositoryAPIAPIService) PatchSubmodelAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, submodel types.ISubmodel, level string) (gen.ImplResponse, error) {
	return gen.Response(http.StatusNotImplemented, nil), errors.New("PatchSubmodelAasRepository method not implemented")
}

// GetSubmodelByIdMetadataAasRepository - Returns the Submodel&#39;s metadata elements
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetSubmodelByIdMetadataAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string) (gen.ImplResponse, error) {
	// TODO - update GetSubmodelByIdMetadataAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, SubmodelMetadata{}) or use other options such as http.Ok ...
	// return types.Response(200, SubmodelMetadata{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("GetSubmodelByIdMetadataAasRepository method not implemented")
}

// PatchSubmodelByIdMetadataAasRepository - Updates the metadata attributes of the Submodel
func (s *AssetAdministrationShellRepositoryAPIAPIService) PatchSubmodelByIdMetadataAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, submodelMetadata gen.SubmodelMetadata) (gen.ImplResponse, error) {
	// TODO - update PatchSubmodelByIdMetadataAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(204, {}) or use other options such as http.Ok ...
	// return types.Response(204, nil),nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("PatchSubmodelByIdMetadataAasRepository method not implemented")
}

// GetSubmodelByIdValueOnlyAasRepository - Returns the Submodel&#39;s ValueOnly representation
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetSubmodelByIdValueOnlyAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, level string, extent string) (gen.ImplResponse, error) {
	// TODO - update GetSubmodelByIdValueOnlyAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, map[string]any{}) or use other options such as http.Ok ...
	// return types.Response(200, map[string]any{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("GetSubmodelByIdValueOnlyAasRepository method not implemented")
}

// PatchSubmodelByIdValueOnlyAasRepository - Updates the values of the Submodel
func (s *AssetAdministrationShellRepositoryAPIAPIService) PatchSubmodelByIdValueOnlyAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, body map[string]any, level string) (gen.ImplResponse, error) {
	// TODO - update PatchSubmodelByIdValueOnlyAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(204, {}) or use other options such as http.Ok ...
	// return types.Response(204, nil),nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("PatchSubmodelByIdValueOnlyAasRepository method not implemented")
}

// GetSubmodelByIdReferenceAasRepository - Returns the Submodel as a Reference
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetSubmodelByIdReferenceAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string) (gen.ImplResponse, error) {
	// TODO - update GetSubmodelByIdReferenceAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, Reference{}) or use other options such as http.Ok ...
	// return types.Response(200, Reference{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("GetSubmodelByIdReferenceAasRepository method not implemented")
}

// GetSubmodelByIdPathAasRepository - Returns the elements of this submodel in path notation.
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetSubmodelByIdPathAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, level string) (gen.ImplResponse, error) {
	// TODO - update GetSubmodelByIdPathAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, []string{}) or use other options such as http.Ok ...
	// return types.Response(200, []string{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("GetSubmodelByIdPathAasRepository method not implemented")
}

// GetAllSubmodelElementsAasRepository - Returns all submodel elements including their hierarchy
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetAllSubmodelElementsAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, limit int32, cursor string, level string, extent string) (gen.ImplResponse, error) {
	// TODO - update GetAllSubmodelElementsAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, GetSubmodelElementsResult{}) or use other options such as http.Ok ...
	// return types.Response(200, GetSubmodelElementsResult{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("GetAllSubmodelElementsAasRepository method not implemented")
}

// PostSubmodelElementAasRepository - Creates a new submodel element
func (s *AssetAdministrationShellRepositoryAPIAPIService) PostSubmodelElementAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, submodelElement types.ISubmodelElement) (gen.ImplResponse, error) {
	return gen.Response(http.StatusNotImplemented, nil), errors.New("PostSubmodelElementAasRepository method not implemented")
}

// GetAllSubmodelElementsMetadataAasRepository - Returns all submodel elements including their hierarchy
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetAllSubmodelElementsMetadataAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, limit int32, cursor string) (gen.ImplResponse, error) {
	// TODO - update GetAllSubmodelElementsMetadataAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, GetSubmodelElementsMetadataResult{}) or use other options such as http.Ok ...
	// return types.Response(200, GetSubmodelElementsMetadataResult{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("GetAllSubmodelElementsMetadataAasRepository method not implemented")
}

// GetAllSubmodelElementsValueOnlyAasRepository - Returns all submodel elements including their hierarchy in the ValueOnly representation
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetAllSubmodelElementsValueOnlyAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, limit int32, cursor string, level string) (gen.ImplResponse, error) {
	// TODO - update GetAllSubmodelElementsValueOnlyAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, GetSubmodelElementsValueResult{}) or use other options such as http.Ok ...
	// return types.Response(200, GetSubmodelElementsValueResult{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("GetAllSubmodelElementsValueOnlyAasRepository method not implemented")
}

// GetAllSubmodelElementsReferenceAasRepository - Returns all submodel elements as a list of References
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetAllSubmodelElementsReferenceAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, limit int32, cursor string, level string) (gen.ImplResponse, error) {
	// TODO - update GetAllSubmodelElementsReferenceAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, GetReferencesResult{}) or use other options such as http.Ok ...
	// return types.Response(200, GetReferencesResult{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("GetAllSubmodelElementsReferenceAasRepository method not implemented")
}

// GetAllSubmodelElementsPathAasRepository - Returns all submodel elements including their hierarchy
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetAllSubmodelElementsPathAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, limit int32, cursor string, level string, extent string) (gen.ImplResponse, error) {
	// TODO - update GetAllSubmodelElementsPathAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, GetPathItemsResult{}) or use other options such as http.Ok ...
	// return types.Response(200, GetPathItemsResult{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("GetAllSubmodelElementsPathAasRepository method not implemented")
}

// GetSubmodelElementByPathAasRepository - Returns a specific submodel element from the Submodel at a specified path
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetSubmodelElementByPathAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string, level string, extent string) (gen.ImplResponse, error) {
	// TODO - update GetSubmodelElementByPathAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, SubmodelElement{}) or use other options such as http.Ok ...
	// return types.Response(200, SubmodelElement{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("GetSubmodelElementByPathAasRepository method not implemented")
}

// PutSubmodelElementByPathAasRepository - Creates or updates an existing submodel element at a specified path within submodel elements hierarchy
func (s *AssetAdministrationShellRepositoryAPIAPIService) PutSubmodelElementByPathAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string, submodelElement types.ISubmodelElement) (gen.ImplResponse, error) {
	// TODO - update PutSubmodelElementByPathAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(201, SubmodelElement{}) or use other options such as http.Ok ...
	// return types.Response(201, SubmodelElement{}), nil

	// TODO: Uncomment the next line to return response gen.Response(204, {}) or use other options such as http.Ok ...
	// return types.Response(204, nil),nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("PutSubmodelElementByPathAasRepository method not implemented")
}

// PostSubmodelElementByPathAasRepository - Creates a new submodel element at a specified path within submodel elements hierarchy
func (s *AssetAdministrationShellRepositoryAPIAPIService) PostSubmodelElementByPathAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string, submodelElement types.ISubmodelElement) (gen.ImplResponse, error) {
	// TODO - update PostSubmodelElementByPathAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(201, SubmodelElement{}) or use other options such as http.Ok ...
	// return types.Response(201, SubmodelElement{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(409, Result{}) or use other options such as http.Ok ...
	// return types.Response(409, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("PostSubmodelElementByPathAasRepository method not implemented")
}

// DeleteSubmodelElementByPathAasRepository - Deletes a submodel element at a specified path within the submodel elements hierarchy
func (s *AssetAdministrationShellRepositoryAPIAPIService) DeleteSubmodelElementByPathAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string) (gen.ImplResponse, error) {
	// TODO - update DeleteSubmodelElementByPathAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(204, {}) or use other options such as http.Ok ...
	// return types.Response(204, nil),nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("DeleteSubmodelElementByPathAasRepository method not implemented")
}

// PatchSubmodelElementValueByPathAasRepository - Updates an existing submodel element value at a specified path within submodel elements hierarchy
func (s *AssetAdministrationShellRepositoryAPIAPIService) PatchSubmodelElementValueByPathAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string, submodelElement types.ISubmodelElement, level string) (gen.ImplResponse, error) {
	// TODO - update PatchSubmodelElementValueByPathAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(204, {}) or use other options such as http.Ok ...
	// return types.Response(204, nil),nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("PatchSubmodelElementValueByPathAasRepository method not implemented")
}

// GetSubmodelElementByPathMetadataAasRepository - Returns the metadata attributes if a specific submodel element from the Submodel at a specified path
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetSubmodelElementByPathMetadataAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string) (gen.ImplResponse, error) {
	// TODO - update GetSubmodelElementByPathMetadataAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, SubmodelElementMetadata{}) or use other options such as http.Ok ...
	// return types.Response(200, SubmodelElementMetadata{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("GetSubmodelElementByPathMetadataAasRepository method not implemented")
}

// PatchSubmodelElementValueByPathMetadata - Updates the metadata attributes of an existing submodel element value at a specified path within submodel elements hierarchy
func (s *AssetAdministrationShellRepositoryAPIAPIService) PatchSubmodelElementValueByPathMetadata(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string, submodelElementMetadata gen.SubmodelElementMetadata) (gen.ImplResponse, error) {
	// TODO - update PatchSubmodelElementValueByPathMetadata with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(204, {}) or use other options such as http.Ok ...
	// return types.Response(204, nil),nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("PatchSubmodelElementValueByPathMetadata method not implemented")
}

// GetSubmodelElementByPathValueOnlyAasRepository - Returns a specific submodel element from the Submodel at a specified path in the ValueOnly representation
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetSubmodelElementByPathValueOnlyAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string, level string, extent string) (gen.ImplResponse, error) {
	// TODO - update GetSubmodelElementByPathValueOnlyAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, SubmodelElementValue{}) or use other options such as http.Ok ...
	// return types.Response(200, SubmodelElementValue{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("GetSubmodelElementByPathValueOnlyAasRepository method not implemented")
}

// PatchSubmodelElementValueByPathValueOnly - Updates the value of an existing submodel element value at a specified path within submodel elements hierarchy
func (s *AssetAdministrationShellRepositoryAPIAPIService) PatchSubmodelElementValueByPathValueOnly(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string, submodelElementValue gen.SubmodelElementValue, level string) (gen.ImplResponse, error) {
	// TODO - update PatchSubmodelElementValueByPathValueOnly with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(204, {}) or use other options such as http.Ok ...
	// return types.Response(204, nil),nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("PatchSubmodelElementValueByPathValueOnly method not implemented")
}

// GetSubmodelElementByPathReferenceAasRepository - Returns the Reference of a specific submodel element from the Submodel at a specified path
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetSubmodelElementByPathReferenceAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string, level string) (gen.ImplResponse, error) {
	// TODO - update GetSubmodelElementByPathReferenceAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, Reference{}) or use other options such as http.Ok ...
	// return types.Response(200, Reference{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("GetSubmodelElementByPathReferenceAasRepository method not implemented")
}

// GetSubmodelElementByPathPathAasRepository - Returns a specific submodel element from the Submodel at a specified path in the Path notation
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetSubmodelElementByPathPathAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string, level string) (gen.ImplResponse, error) {
	// TODO - update GetSubmodelElementByPathPathAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, []string{}) or use other options such as http.Ok ...
	// return types.Response(200, []string{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("GetSubmodelElementByPathPathAasRepository method not implemented")
}

// GetFileByPathAasRepository - Downloads file content from a specific submodel element from the Submodel at a specified path
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetFileByPathAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string) (gen.ImplResponse, error) {
	// TODO - update GetFileByPathAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, *os.File{}) or use other options such as http.Ok ...
	// return types.Response(200, *os.File{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("GetFileByPathAasRepository method not implemented")
}

// PutFileByPathAasRepository - Uploads file content to an existing submodel element at a specified path within submodel elements hierarchy
func (s *AssetAdministrationShellRepositoryAPIAPIService) PutFileByPathAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string, fileName string, file *os.File) (gen.ImplResponse, error) {
	// TODO - update PutFileByPathAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(204, {}) or use other options such as http.Ok ...
	// return types.Response(204, nil),nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("PutFileByPathAasRepository method not implemented")
}

// DeleteFileByPathAasRepository - Deletes file content of an existing submodel element at a specified path within submodel elements hierarchy
func (s *AssetAdministrationShellRepositoryAPIAPIService) DeleteFileByPathAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string) (gen.ImplResponse, error) {
	// TODO - update DeleteFileByPathAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, {}) or use other options such as http.Ok ...
	// return types.Response(200, nil),nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("DeleteFileByPathAasRepository method not implemented")
}

// InvokeOperationAasRepository - Synchronously invokes an Operation at a specified path
func (s *AssetAdministrationShellRepositoryAPIAPIService) InvokeOperationAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string, operationRequest gen.OperationRequest) (gen.ImplResponse, error) {
	// TODO - update InvokeOperationAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, OperationResult{}) or use other options such as http.Ok ...
	// return types.Response(200, OperationResult{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("InvokeOperationAasRepository method not implemented")
}

// InvokeOperationValueOnlyAasRepository - Synchronously invokes an Operation at a specified path
func (s *AssetAdministrationShellRepositoryAPIAPIService) InvokeOperationValueOnlyAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string, operationRequestValueOnly gen.OperationRequestValueOnly) (gen.ImplResponse, error) {
	// TODO - update InvokeOperationValueOnlyAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, OperationResultValueOnly{}) or use other options such as http.Ok ...
	// return types.Response(200, OperationResultValueOnly{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("InvokeOperationValueOnlyAasRepository method not implemented")
}

// InvokeOperationAsyncAasRepository - Asynchronously invokes an Operation at a specified path
func (s *AssetAdministrationShellRepositoryAPIAPIService) InvokeOperationAsyncAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string, operationRequest gen.OperationRequest) (gen.ImplResponse, error) {
	// TODO - update InvokeOperationAsyncAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(202, {}) or use other options such as http.Ok ...
	// return types.Response(202, nil),nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("InvokeOperationAsyncAasRepository method not implemented")
}

// InvokeOperationAsyncValueOnlyAasRepository - Asynchronously invokes an Operation at a specified path
func (s *AssetAdministrationShellRepositoryAPIAPIService) InvokeOperationAsyncValueOnlyAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string, operationRequestValueOnly gen.OperationRequestValueOnly) (gen.ImplResponse, error) {
	// TODO - update InvokeOperationAsyncValueOnlyAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(202, {}) or use other options such as http.Ok ...
	// return types.Response(202, nil),nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("InvokeOperationAsyncValueOnlyAasRepository method not implemented")
}

// GetOperationAsyncStatusAasRepository - Returns the Operation status of an asynchronous invoked Operation
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetOperationAsyncStatusAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string, handleId string) (gen.ImplResponse, error) {
	// TODO - update GetOperationAsyncStatusAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, BaseOperationResult{}) or use other options such as http.Ok ...
	// return types.Response(200, BaseOperationResult{}), nil

	// TODO: Uncomment the next line to return response gen.Response(302, {}) or use other options such as http.Ok ...
	// return types.Response(302, nil),nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("GetOperationAsyncStatusAasRepository method not implemented")
}

// GetOperationAsyncResultAasRepository - Returns the Operation result of an asynchronous invoked Operation
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetOperationAsyncResultAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string, handleId string) (gen.ImplResponse, error) {
	// TODO - update GetOperationAsyncResultAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, OperationResult{}) or use other options such as http.Ok ...
	// return types.Response(200, OperationResult{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("GetOperationAsyncResultAasRepository method not implemented")
}

// GetOperationAsyncResultValueOnlyAasRepository - Returns the ValueOnly notation of the Operation result of an asynchronous invoked Operation
func (s *AssetAdministrationShellRepositoryAPIAPIService) GetOperationAsyncResultValueOnlyAasRepository(ctx context.Context, aasIdentifier string, submodelIdentifier string, idShortPath string, handleId string) (gen.ImplResponse, error) {
	// TODO - update GetOperationAsyncResultValueOnlyAasRepository with the required logic for this service method.
	// Add api_asset_administration_shell_repository_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response gen.Response(200, OperationResultValueOnly{}) or use other options such as http.Ok ...
	// return types.Response(200, OperationResultValueOnly{}), nil

	// TODO: Uncomment the next line to return response gen.Response(400, Result{}) or use other options such as http.Ok ...
	// return types.Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(401, Result{}) or use other options such as http.Ok ...
	// return types.Response(401, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(403, Result{}) or use other options such as http.Ok ...
	// return types.Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(404, Result{}) or use other options such as http.Ok ...
	// return types.Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(500, Result{}) or use other options such as http.Ok ...
	// return types.Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response gen.Response(0, Result{}) or use other options such as http.Ok ...
	// return types.Response(0, Result{}), nil

	return gen.Response(http.StatusNotImplemented, nil), errors.New("GetOperationAsyncResultValueOnlyAasRepository method not implemented")
}
