// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * DotAAS Part 2 | HTTP/REST | Concept Description Repository Service Specification
 *
 * The ConceptDescription Repository Service Specification as part of [Specification of the Asset Administration Shell: Part 2](https://industrialdigitaltwin.org/en/content-hub/aasspecifications).   Copyright: Industrial Digital Twin Association (IDTA) March 2023
 *
 * API version: V3.1.1_SSP-001
 * Contact: info@idtwin.org
 */

package openapi

import (
	"context"
	"net/http"

	"github.com/aas-core-works/aas-core3.1-golang/types"
	"github.com/eclipse-basyx/basyx-go-components/internal/common/model"
)

// ConceptDescriptionRepositoryAPIAPIRouter defines the required methods for binding the api requests to a responses for the ConceptDescriptionRepositoryAPIAPI
// The ConceptDescriptionRepositoryAPIAPIRouter implementation should parse necessary information from the http request,
// pass the data to a ConceptDescriptionRepositoryAPIAPIServicer to perform the required actions, then write the service results to the http response.
type ConceptDescriptionRepositoryAPIAPIRouter interface {
	GetAllConceptDescriptions(http.ResponseWriter, *http.Request)
	PostConceptDescription(http.ResponseWriter, *http.Request)
	GetConceptDescriptionById(http.ResponseWriter, *http.Request)
	PutConceptDescriptionById(http.ResponseWriter, *http.Request)
	DeleteConceptDescriptionById(http.ResponseWriter, *http.Request)
}

// DescriptionAPIAPIRouter defines the required methods for binding the api requests to a responses for the DescriptionAPIAPI
// The DescriptionAPIAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DescriptionAPIAPIServicer to perform the required actions, then write the service results to the http response.
type DescriptionAPIAPIRouter interface {
	GetSelfDescription(http.ResponseWriter, *http.Request)
}

// SerializationAPIAPIRouter defines the required methods for binding the api requests to a responses for the SerializationAPIAPI
// The SerializationAPIAPIRouter implementation should parse necessary information from the http request,
// pass the data to a SerializationAPIAPIServicer to perform the required actions, then write the service results to the http response.
type SerializationAPIAPIRouter interface {
	GenerateSerializationByIds(http.ResponseWriter, *http.Request)
}

// ConceptDescriptionRepositoryAPIAPIServicer defines the api actions for the ConceptDescriptionRepositoryAPIAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ConceptDescriptionRepositoryAPIAPIServicer interface {
	GetAllConceptDescriptions(context.Context, string, string, string, int32, string) (model.ImplResponse, error)
	PostConceptDescription(context.Context, types.IConceptDescription) (model.ImplResponse, error)
	GetConceptDescriptionById(context.Context, string) (model.ImplResponse, error)
	PutConceptDescriptionById(context.Context, string, types.IConceptDescription) (model.ImplResponse, error)
	DeleteConceptDescriptionById(context.Context, string) (model.ImplResponse, error)
}

// DescriptionAPIAPIServicer defines the api actions for the DescriptionAPIAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DescriptionAPIAPIServicer interface {
	GetSelfDescription(context.Context) (model.ImplResponse, error)
}
