// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * DotAAS Part 2 | HTTP/REST | Concept Description Repository Service Specification
 *
 * The ConceptDescription Repository Service Specification as part of [Specification of the Asset Administration Shell: Part 2](https://industrialdigitaltwin.org/en/content-hub/aasspecifications).   Copyright: Industrial Digital Twin Association (IDTA) March 2023
 *
 * API version: V3.1.1_SSP-001
 * Contact: info@idtwin.org
 */

package openapi

import (
	"encoding/json"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/aas-core-works/aas-core3.1-golang/jsonization"
	"github.com/eclipse-basyx/basyx-go-components/internal/common/model"
	"github.com/go-chi/chi/v5"
)

// ConceptDescriptionRepositoryAPIAPIController binds http requests to an api service and writes the service results to the http response
type ConceptDescriptionRepositoryAPIAPIController struct {
	service            ConceptDescriptionRepositoryAPIAPIServicer
	errorHandler       model.ErrorHandler
	contextPath        string
	strictVerification bool
}

// ConceptDescriptionRepositoryAPIAPIOption for how the controller is set up.
type ConceptDescriptionRepositoryAPIAPIOption func(*ConceptDescriptionRepositoryAPIAPIController)

// WithConceptDescriptionRepositoryAPIAPIErrorHandler inject ErrorHandler into controller
func WithConceptDescriptionRepositoryAPIAPIErrorHandler(h model.ErrorHandler) ConceptDescriptionRepositoryAPIAPIOption {
	return func(c *ConceptDescriptionRepositoryAPIAPIController) {
		c.errorHandler = h
	}
}

// NewConceptDescriptionRepositoryAPIAPIController creates a default api controller
func NewConceptDescriptionRepositoryAPIAPIController(s ConceptDescriptionRepositoryAPIAPIServicer, contextPath string, strictVerification bool) *ConceptDescriptionRepositoryAPIAPIController {
	controller := &ConceptDescriptionRepositoryAPIAPIController{
		service:            s,
		errorHandler:       model.DefaultErrorHandler,
		contextPath:        contextPath,
		strictVerification: strictVerification,
	}

	return controller
}

// Routes returns all the api routes for the ConceptDescriptionRepositoryAPIAPIController
func (c *ConceptDescriptionRepositoryAPIAPIController) Routes() model.Routes {
	return model.Routes{
		"GetAllConceptDescriptions":    model.Route{Name: "GetAllConceptDescriptions", Method: strings.ToUpper("Get"), Pattern: c.contextPath + "/concept-descriptions", HandlerFunc: c.GetAllConceptDescriptions},
		"PostConceptDescription":       model.Route{Name: "PostConceptDescription", Method: strings.ToUpper("Post"), Pattern: c.contextPath + "/concept-descriptions", HandlerFunc: c.PostConceptDescription},
		"GetConceptDescriptionById":    model.Route{Name: "GetConceptDescriptionById", Method: strings.ToUpper("Get"), Pattern: c.contextPath + "/concept-descriptions/{cdIdentifier}", HandlerFunc: c.GetConceptDescriptionById},
		"PutConceptDescriptionById":    model.Route{Name: "PutConceptDescriptionById", Method: strings.ToUpper("Put"), Pattern: c.contextPath + "/concept-descriptions/{cdIdentifier}", HandlerFunc: c.PutConceptDescriptionById},
		"DeleteConceptDescriptionById": model.Route{Name: "DeleteConceptDescriptionById", Method: strings.ToUpper("Delete"), Pattern: c.contextPath + "/concept-descriptions/{cdIdentifier}", HandlerFunc: c.DeleteConceptDescriptionById},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the ConceptDescriptionRepositoryAPIAPIController
func (c *ConceptDescriptionRepositoryAPIAPIController) OrderedRoutes() []model.Route {
	return []model.Route{
		model.Route{Name: "GetAllConceptDescriptions", Method: strings.ToUpper("Get"), Pattern: c.contextPath + "/concept-descriptions", HandlerFunc: c.GetAllConceptDescriptions},
		model.Route{Name: "PostConceptDescription", Method: strings.ToUpper("Post"), Pattern: c.contextPath + "/concept-descriptions", HandlerFunc: c.PostConceptDescription},
		model.Route{Name: "GetConceptDescriptionById", Method: strings.ToUpper("Get"), Pattern: c.contextPath + "/concept-descriptions/{cdIdentifier}", HandlerFunc: c.GetConceptDescriptionById},
		model.Route{Name: "PutConceptDescriptionById", Method: strings.ToUpper("Put"), Pattern: c.contextPath + "/concept-descriptions/{cdIdentifier}", HandlerFunc: c.PutConceptDescriptionById},
		model.Route{Name: "DeleteConceptDescriptionById", Method: strings.ToUpper("Delete"), Pattern: c.contextPath + "/concept-descriptions/{cdIdentifier}", HandlerFunc: c.DeleteConceptDescriptionById},
	}
}

// GetAllConceptDescriptions - Returns all Concept Descriptions
func (c *ConceptDescriptionRepositoryAPIAPIController) GetAllConceptDescriptions(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &model.ParsingError{Err: err}, nil)
		return
	}
	var idShortParam string
	if query.Has("idShort") {
		param := query.Get("idShort")

		idShortParam = param
	} else {
	}
	var isCaseOfParam string
	if query.Has("isCaseOf") {
		param := query.Get("isCaseOf")

		isCaseOfParam = param
	} else {
	}
	var dataSpecificationRefParam string
	if query.Has("dataSpecificationRef") {
		param := query.Get("dataSpecificationRef")

		dataSpecificationRefParam = param
	} else {
	}
	var limitParam int32
	if query.Has("limit") {
		param, err := parseNumericParameter[int32](
			query.Get("limit"),
			model.WithParse[int32](parseInt32),
			model.WithMinimum[int32](1),
		)
		if err != nil {
			c.errorHandler(w, r, &model.ParsingError{Param: "limit", Err: err}, nil)
			return
		}

		limitParam = param
	} else {
	}
	var cursorParam string
	if query.Has("cursor") {
		param := query.Get("cursor")

		cursorParam = param
	} else {
	}
	result, err := c.service.GetAllConceptDescriptions(r.Context(), idShortParam, isCaseOfParam, dataSpecificationRefParam, limitParam, cursorParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = model.EncodeJSONResponse(result.Body, &result.Code, w)
}

// PostConceptDescription - Creates a new Concept Description
func (c *ConceptDescriptionRepositoryAPIAPIController) PostConceptDescription(w http.ResponseWriter, r *http.Request) {
	// Read and unmarshal JSON to interface{} first
	bodyBytes, err := io.ReadAll(r.Body)
	if err != nil {
		c.errorHandler(w, r, &model.ParsingError{Err: err}, nil)
		return
	}
	var jsonable interface{}
	if err := json.Unmarshal(bodyBytes, &jsonable); err != nil {
		c.errorHandler(w, r, &model.ParsingError{Err: err}, nil)
		return
	}
	conceptDescriptionParam, err := jsonization.ConceptDescriptionFromJsonable(jsonable)
	if err != nil {
		c.errorHandler(w, r, &model.ParsingError{Err: err}, nil)
		return
	}

	result, err := c.service.PostConceptDescription(r.Context(), conceptDescriptionParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = model.EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetConceptDescriptionById - Returns a specific Concept Description
func (c *ConceptDescriptionRepositoryAPIAPIController) GetConceptDescriptionById(w http.ResponseWriter, r *http.Request) {
	cdIdentifierParam := chi.URLParam(r, "cdIdentifier")
	if cdIdentifierParam == "" {
		c.errorHandler(w, r, &model.RequiredError{Field: "cdIdentifier"}, nil)
		return
	}
	result, err := c.service.GetConceptDescriptionById(r.Context(), cdIdentifierParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = model.EncodeJSONResponse(result.Body, &result.Code, w)
}

// PutConceptDescriptionById - Creates or updates an existing Concept Description
func (c *ConceptDescriptionRepositoryAPIAPIController) PutConceptDescriptionById(w http.ResponseWriter, r *http.Request) {
	cdIdentifierParam := chi.URLParam(r, "cdIdentifier")
	if cdIdentifierParam == "" {
		c.errorHandler(w, r, &model.RequiredError{Field: "cdIdentifier"}, nil)
		return
	}
	// Read and unmarshal JSON to interface{} first
	bodyBytes, err := io.ReadAll(r.Body)
	if err != nil {
		c.errorHandler(w, r, &model.ParsingError{Err: err}, nil)
		return
	}
	var jsonable interface{}
	if err := json.Unmarshal(bodyBytes, &jsonable); err != nil {
		c.errorHandler(w, r, &model.ParsingError{Err: err}, nil)
		return
	}
	conceptDescriptionParam, err := jsonization.ConceptDescriptionFromJsonable(jsonable)
	if err != nil {
		c.errorHandler(w, r, &model.ParsingError{Err: err}, nil)
		return
	}

	result, err := c.service.PutConceptDescriptionById(r.Context(), cdIdentifierParam, conceptDescriptionParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = model.EncodeJSONResponse(result.Body, &result.Code, w)
}

// DeleteConceptDescriptionById - Deletes a Concept Description
func (c *ConceptDescriptionRepositoryAPIAPIController) DeleteConceptDescriptionById(w http.ResponseWriter, r *http.Request) {
	cdIdentifierParam := chi.URLParam(r, "cdIdentifier")
	if cdIdentifierParam == "" {
		c.errorHandler(w, r, &model.RequiredError{Field: "cdIdentifier"}, nil)
		return
	}
	result, err := c.service.DeleteConceptDescriptionById(r.Context(), cdIdentifierParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = model.EncodeJSONResponse(result.Body, &result.Code, w)
}

// parseQuery parses query parameters and returns an error if any malformed value pairs are encountered.
func parseQuery(rawQuery string) (url.Values, error) {
	return url.ParseQuery(rawQuery)
}

func parseNumericParameter[T model.Number](param string, fn model.HOperation[T], checks ...model.Constraint[T]) (T, error) {
	v, ok, err := fn(param)
	if err != nil {
		return 0, err
	}

	if !ok {
		for _, check := range checks {
			if err := check(v); err != nil {
				return 0, err
			}
		}
	}

	return v, nil
}

func parseInt32(param string) (int32, error) {
	if param == "" {
		return 0, nil
	}

	val, err := strconv.ParseInt(param, 10, 32)
	return int32(val), err
}
