// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package companylookupapi

import (
	"context"
	"net/http"

	"github.com/eclipse-basyx/basyx-go-components/internal/common/model"
)

// CompanyLookupAPIAPIRouter defines the required methods for binding API requests to responses for the Company Lookup API.
// The CompanyLookupAPIAPIRouter implementation should parse necessary information from the HTTP request,
// pass the data to a CompanyLookupAPIAPIServicer to perform the required actions, then write the service results to the HTTP response.
type CompanyLookupAPIAPIRouter interface {
	GetAllCompanyDescriptors(http.ResponseWriter, *http.Request)
	PostCompanyDescriptor(http.ResponseWriter, *http.Request)
	GetCompanyDescriptorById(http.ResponseWriter, *http.Request)
	PutCompanyDescriptorById(http.ResponseWriter, *http.Request)
	DeleteCompanyDescriptorById(http.ResponseWriter, *http.Request)
}

// DescriptionAPIAPIRouter defines the required methods for binding API requests to responses for the description API.
// The DescriptionAPIAPIRouter implementation should parse necessary information from the HTTP request,
// pass the data to a DescriptionAPIAPIServicer to perform the required actions, then write the service results to the HTTP response.
type DescriptionAPIAPIRouter interface {
	GetDescription(http.ResponseWriter, *http.Request)
}

// CompanyLookupAPIAPIServicer defines the API actions for the Company Lookup service.
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type CompanyLookupAPIAPIServicer interface {
	GetAllCompanyDescriptors(context.Context, int32, string, string, string) (model.ImplResponse, error)
	PostCompanyDescriptor(context.Context, model.CompanyDescriptor) (model.ImplResponse, error)
	GetCompanyDescriptorById(context.Context, string) (model.ImplResponse, error)
	PutCompanyDescriptorById(context.Context, string, model.CompanyDescriptor) (model.ImplResponse, error)
	DeleteCompanyDescriptorById(context.Context, string) (model.ImplResponse, error)
}

// DescriptionAPIAPIServicer defines the API actions for the description service.
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DescriptionAPIAPIServicer interface {
	GetDescription(context.Context) (model.ImplResponse, error)
}
