// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package companylookupapi

import (
	"encoding/json"
	"errors"
	"log"
	"net/http"
	"strings"

	"github.com/eclipse-basyx/basyx-go-components/internal/common"
	"github.com/eclipse-basyx/basyx-go-components/internal/common/model"
	"github.com/go-chi/chi/v5"
)

const (
	componentName = "ComLookup"
)

type companyDescriptorEnvelope struct {
	Data *model.CompanyDescriptor `json:"data"`
}

func decodeCompanyDescriptorEnvelope(r *http.Request) (model.CompanyDescriptor, error) {
	var envelope companyDescriptorEnvelope
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&envelope); err != nil {
		return model.CompanyDescriptor{}, err
	}
	if envelope.Data == nil {
		return model.CompanyDescriptor{}, errors.New("missing required field: data")
	}

	return *envelope.Data, nil
}

// CompanyLookupAPIAPIController binds HTTP requests to an API service and writes the service results to the HTTP response.
type CompanyLookupAPIAPIController struct {
	service      CompanyLookupAPIAPIServicer
	errorHandler model.ErrorHandler
}

// CompanyLookupAPIAPIOption controls how the controller is set up.
type CompanyLookupAPIAPIOption func(*CompanyLookupAPIAPIController)

// WithCompanyLookupAPIAPIErrorHandler injects ErrorHandler into the controller.
func WithCompanyLookupAPIAPIErrorHandler(h model.ErrorHandler) CompanyLookupAPIAPIOption {
	return func(c *CompanyLookupAPIAPIController) {
		c.errorHandler = h
	}
}

// NewCompanyLookupAPIAPIController creates a default API controller.
func NewCompanyLookupAPIAPIController(s CompanyLookupAPIAPIServicer, opts ...CompanyLookupAPIAPIOption) *CompanyLookupAPIAPIController {
	controller := &CompanyLookupAPIAPIController{
		service:      s,
		errorHandler: model.DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all API routes for the CompanyLookupAPIAPIController.
func (c *CompanyLookupAPIAPIController) Routes() Routes {
	return Routes{
		"GetAllCompanyDescriptors": Route{
			strings.ToUpper("Get"),
			"/companies",
			c.GetAllCompanyDescriptors,
		},
		"PostCompanyDescriptor": Route{
			strings.ToUpper("Post"),
			"/companies",
			c.PostCompanyDescriptor,
		},
		"GetCompanyDescriptorById": Route{
			strings.ToUpper("Get"),
			"/companies/{companyIdentifier}",
			c.GetCompanyDescriptorById,
		},
		"PutCompanyDescriptorById": Route{
			strings.ToUpper("Put"),
			"/companies/{companyIdentifier}",
			c.PutCompanyDescriptorById,
		},
		"DeleteCompanyDescriptorById": Route{
			strings.ToUpper("Delete"),
			"/companies/{companyIdentifier}",
			c.DeleteCompanyDescriptorById,
		},
	}
}

// GetAllCompanyDescriptors returns all company descriptors.
func (c *CompanyLookupAPIAPIController) GetAllCompanyDescriptors(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		log.Printf("📍 [%s] Error in GetAllCompanyDescriptors: parse query raw=%q: %v", componentName, r.URL.RawQuery, err)
		result := common.NewErrorResponse(
			err,
			http.StatusBadRequest,
			componentName,
			"GetAllCompanyDescriptors",
			"query",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	var limitParam int32
	if query.Has("limit") {
		param, err := parseNumericParameter[int32](
			query.Get("limit"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
		)
		if err != nil {
			log.Printf("📍 [%s] Error in GetAllCompanyDescriptors: parse limit=%q: %v", componentName, query.Get("limit"), err)
			result := common.NewErrorResponse(
				err,
				http.StatusBadRequest,
				componentName,
				"GetAllCompanyDescriptors",
				"limit",
			)
			_ = EncodeJSONResponse(result.Body, &result.Code, w)
			return
		}
		limitParam = param
	}
	var cursorParam string
	if query.Has("cursor") {
		cursorParam = query.Get("cursor")
	}
	var nameParam string
	if query.Has("name") {
		nameParam = query.Get("name")
	}
	var assetIdParam string
	if query.Has("assetId") {
		assetIdParam = query.Get("assetId")
	}

	result, err := c.service.GetAllCompanyDescriptors(r.Context(), limitParam, cursorParam, nameParam, assetIdParam)
	if err != nil {
		log.Printf("📍 [%s] Error in GetAllCompanyDescriptors: service failure (limit=%d cursor=%q name=%q assetId=%q): %v", componentName, limitParam, cursorParam, nameParam, assetIdParam, err)
		c.errorHandler(w, r, err, &result)
		return
	}
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// PostCompanyDescriptor creates a new company descriptor.
func (c *CompanyLookupAPIAPIController) PostCompanyDescriptor(w http.ResponseWriter, r *http.Request) {
	companyDescriptorParam, err := decodeCompanyDescriptorEnvelope(r)
	if err != nil {
		log.Printf("📍 [%s] Error in PostCompanyDescriptor: decode body: %v", componentName, err)
		result := common.NewErrorResponse(
			err,
			http.StatusBadRequest,
			componentName,
			"PostCompanyDescriptor",
			"RequestBody",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}

	if err := model.AssertCompanyDescriptorRequired(companyDescriptorParam); err != nil {
		log.Printf("📍 [%s] Error in PostCompanyDescriptor: required validation failed: %v", componentName, err)
		result := common.NewErrorResponse(
			err,
			http.StatusBadRequest,
			componentName,
			"PostCompanyDescriptor",
			"RequestBody",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	if !model.IsStrictCompanyDomain(companyDescriptorParam.Domain) {
		invalidDomainErr := common.NewErrBadRequest("COMLOOKUP-POSTCOMPANYDESCRIPTOR-VALIDATEDOMAIN provided domain is not a syntactically valid domain")
		log.Printf("📍 [%s] Error in PostCompanyDescriptor: invalid domain syntax in body (companyDomain=%q)", componentName, companyDescriptorParam.Domain)
		result := common.NewErrorResponse(
			invalidDomainErr,
			http.StatusBadRequest,
			componentName,
			"PostCompanyDescriptor",
			"RequestBody-InvalidDomainSyntax",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	if err := model.AssertCompanyDescriptorConstraints(companyDescriptorParam); err != nil {
		log.Printf("📍 [%s] Error in PostCompanyDescriptor: constraints validation failed: %v", componentName, err)
		result := common.NewErrorResponse(
			err,
			http.StatusBadRequest,
			componentName,
			"PostCompanyDescriptor",
			"RequestBody",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	result, err := c.service.PostCompanyDescriptor(r.Context(), companyDescriptorParam)
	if err != nil {
		log.Printf("📍 [%s] Error in PostCompanyDescriptor: service failure (bodyDomain=%q): %v", componentName, companyDescriptorParam.Domain, err)
		c.errorHandler(w, r, err, &result)
		return
	}
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetCompanyDescriptorById returns a specific company descriptor.
func (c *CompanyLookupAPIAPIController) GetCompanyDescriptorById(w http.ResponseWriter, r *http.Request) {

	companyIdentifierParam := chi.URLParam(r, "companyIdentifier")
	if companyIdentifierParam == "" {
		log.Printf("📍 [%s] Error in GetCompanyDescriptorById: missing path parameter companyIdentifier", componentName)
		result := common.NewErrorResponse(
			common.NewErrBadRequest("Missing path parameter 'companyIdentifier'"),
			http.StatusBadRequest,
			componentName,
			"GetCompanyDescriptorById",
			"companyIdentifier",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	result, err := c.service.GetCompanyDescriptorById(r.Context(), companyIdentifierParam)
	if err != nil {
		log.Printf("📍 [%s] Error in GetCompanyDescriptorById: service failure (companyIdentifier=%q): %v", componentName, companyIdentifierParam, err)
		c.errorHandler(w, r, err, &result)
		return
	}
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// PutCompanyDescriptorById creates or updates an existing company descriptor.
func (c *CompanyLookupAPIAPIController) PutCompanyDescriptorById(w http.ResponseWriter, r *http.Request) {
	companyIdentifierParam := chi.URLParam(r, "companyIdentifier")
	if companyIdentifierParam == "" {
		log.Printf("📍 [%s] Error in PutCompanyDescriptorById: missing path parameter companyIdentifier", componentName)
		result := common.NewErrorResponse(
			common.NewErrBadRequest("Missing path parameter 'companyIdentifier'"),
			http.StatusBadRequest,
			componentName,
			"PutCompanyDescriptorById",
			"companyIdentifier",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	companyDescriptorParam, err := decodeCompanyDescriptorEnvelope(r)
	if err != nil {
		log.Printf("📍 [%s] Error in PutCompanyDescriptorById: decode body: %v", componentName, err)
		result := common.NewErrorResponse(
			err,
			http.StatusBadRequest,
			componentName,
			"PutCompanyDescriptorById",
			"RequestBody",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	if err := model.AssertCompanyDescriptorRequired(companyDescriptorParam); err != nil {
		log.Printf("📍 [%s] Error in PutCompanyDescriptorById: required validation failed: %v", componentName, err)
		result := common.NewErrorResponse(
			err,
			http.StatusBadRequest,
			componentName,
			"PutCompanyDescriptorById",
			"RequestBody",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	if err := model.AssertCompanyDescriptorConstraints(companyDescriptorParam); err != nil {
		log.Printf("📍 [%s] Error in PutCompanyDescriptorById: constraints validation failed: %v", componentName, err)
		result := common.NewErrorResponse(
			err,
			http.StatusBadRequest,
			componentName,
			"PutCompanyDescriptorById",
			"RequestBody",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	result, err := c.service.PutCompanyDescriptorById(r.Context(), companyIdentifierParam, companyDescriptorParam)
	if err != nil {
		log.Printf("📍 [%s] Error in PutCompanyDescriptorById: service failure (companyIdentifier=%q bodyDomain=%q): %v", componentName, companyIdentifierParam, companyDescriptorParam.Domain, err)
		c.errorHandler(w, r, err, &result)
		return
	}
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// DeleteCompanyDescriptorById deletes a company descriptor.
func (c *CompanyLookupAPIAPIController) DeleteCompanyDescriptorById(w http.ResponseWriter, r *http.Request) {
	companyIdentifierParam := chi.URLParam(r, "companyIdentifier")
	if companyIdentifierParam == "" {
		log.Printf("📍 [%s] Error in DeleteCompanyDescriptorById: missing path parameter companyIdentifier", componentName)
		result := common.NewErrorResponse(
			common.NewErrBadRequest("Missing path parameter 'companyIdentifier'"),
			http.StatusBadRequest,
			componentName,
			"DeleteCompanyDescriptorById",
			"companyIdentifier",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	result, err := c.service.DeleteCompanyDescriptorById(r.Context(), companyIdentifierParam)
	if err != nil {
		log.Printf("📍 [%s] Error in DeleteCompanyDescriptorById: service failure (companyIdentifier=%q): %v", componentName, companyIdentifierParam, err)
		c.errorHandler(w, r, err, &result)
		return
	}
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
